### ISSUE TITLE
Missed Calls

### ISSUE THREAD

**Issue by CFenner** [paviro/MMM-FRITZ-Box-Callmonitor#7]
I'm not so interested in the current calls as the mirror is in the bathroom and I just have a look into it every morning. But is it possible to display missed calls?

**Comment by paviro** [comment]
Not sure, will have to look into the FRITZ!Box :)

**Comment by CFenner** [comment]
I didn't get this module running, but I'll try again this week.

**Comment by paviro** [comment]
Haven't found a method to directly tell if a call was missed, since a voice mail also counts as connected call. I could add a function, so you can configure a minimum time in seconds a call has to be until it is considered not missed. So if your voice mail is about 30 seconds use this as the configuration and any call shorter than that will be considered missed. Would that be useful?

**Comment by paviro** [comment]
Feature is added see README.
